#website pass 
WEB_PASS = "a"

# Authentication
SESSION_SECRET = "0Al/sTAub065P7Vs5XdGOahs64nCbHv9LN/+z1OfCCvWRoVe@d+X5lDU..."

# Database Configuration
DB_NAME = "neondb"
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_sVjku5le6XfH"
DB_HOST = "ep-square-smoke-a81fq7w4-pooler.eastus2.azure.neon.tech"
DB_PORT = "5432"
DATABASE_URL = "postgresql://neondb_owner:npg_sVjku5le6XfH@ep-square-smoke-a81fq7w4-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"

# Imgbb API Configuration
IMGBB_API_KEY = "ec519cb1c1643a46e16f22fe58a256cb"